### PR TITLE
Hello Tomasz

### PR DESCRIPTION
**Pull request by DougReynolds**
I've Added scope and snippets for CoffeeScript support in the Sublime-Text-2-Backbone.js-package.  Please review, if you like please pull.  Please feel free to let me know if you find anything problematic, I would be happy to review and fix as needed.

Best to you,

Douglas

### CODE REVIEW

**Comment by tomasztunik** [comment]
Hey Douglas! 

Thanks for the addition - will check it out later today and will pull it in

**Comment by DougReynolds** [comment]
Thanks Tomasz!
Backbone 0.9.2 released yesterday, looks like there are some additions that could be made.  I'll review the updated API today and see about adding any new coffee snips and/or completions.

**Comment by tomasztunik** [comment]
Ah good catch - had old website cached and overlooked it :) will add completions quickly directly from github

**Comment by DougReynolds** [comment]
I just pushed a bunch of coffee snips, am over half way through Model API.  I thought I would try to finish up major API sections, test, and then ping you for a pull request - if you are good with that?  Please feel free to peruse my fork, feedback welcome :-)

**Comment by tomasztunik** [comment]
Just checked them out. I'm wondering if it won't be an overkill for basic snippets/completions plugin to cover whole API, maybe we should make it as a separate one so that people who program in JS only or prefer the good ol' typing don't have to download this huge snippets collection - what do you think? We could then link to it from this repo as a complementary plugin

**Comment by DougReynolds** [comment]
I agree, however, rather than splitting up into two plugins - what do you think of keeping the coffee support? I'll roll back my plugin repo and then create a new repo of coffee snippets for an a-la-carte download that user's could pick from and drop into the plugin.

**Comment by tomasztunik** [comment]
Totally! I love your coffee script addition and would hate see it go! Will follow you to track your snippets development.

**Comment by DougReynolds** [comment]
Done!  Thanks, I removed those snips and placed in separate repo.  Readme is updated to announce availability and link to repo: https://github.com/dougrdotnet/Sublime-Text-2-Backbone.js-Coffee.  let me know if you want to pull anything from the js fork.

**Comment by tomasztunik** [comment]
updated readme.md in place, thanks for the contribution once again Douglas! Remember to register your package with the http://wbond.net/sublime_packages/community

**Comment by DougReynolds** [comment]
I was thinking about that, need to look to see if package manager can install into a sublime packages subdirectory, not sure.  Thank you, if you get any pings on coffee stuff in your issues, lmk, I will support those.  I am following and will try to track issues.

**Comment by DougReynolds** [comment]
If it is possible to install a plugin contents into another directory, would you be opposed to me configuring the coffee snippets to install into the Sublime Text 2 Backbone.js-package directory?  I emailed wbond to see if it is even possible to do it, I am not able to find any configurations available in docs.  It seems tough for the user to install the coffee snippet package and then have to manually move them into the plugin.  They also would need to do this to get updates/additions as well.  Short of creating a separate plugin, I'm not sure of a solution at the moment.

**Pull request merged**
